openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /time:
    get:
      summary: Get the current time
      parameters:
        - name: timezone
          in: query
          description: The timezone to use
          required: false
          schema:
            type: string
      responses:
        200:
          description: A JSON object with the current time
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WsTime'
  /users:
    post:
      summary: Post me
      responses:
        200:
          description: A JSON object of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    get:
      summary: Get a list of users
      security:
        - openId: [ ]
      responses:
        200:
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

components:
  schemas:
    WsTime:
      type: object
      required:
        - time
      properties:
        time:
          type: string
          format: date-time
    User:
      type: object
      required:
        - username
      properties:
        username:
          type: string
        email:
          type: string
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://issuer.example.com/.well-known/openid-configuration