openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        200:
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string